name: sofia_app
description: App to manage my expenses.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  currency_text_input_formatter: ^2.1.10
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
